development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "ENV["REDISTOGO_URL"] || "redis://localhost:6379/"/1" } %>
  channel_prefix: weather_map_production
